#!/bin/bash

# Test script to verify SQLite database creation and data storage

echo "Testing SQLite database functionality..."
echo ""

# Check if we can compile (would need cargo)
echo "1. Database Schema Check:"
echo "   The program creates a table 'blockchain' with columns:"
echo "   - id (INTEGER PRIMARY KEY)"
echo "   - block_index (INTEGER NOT NULL)"
echo "   - timestamp (INTEGER NOT NULL)"
echo "   - data_json (TEXT NOT NULL)"
echo "   - prev_hash (TEXT NOT NULL)"
echo "   - hash (TEXT NOT NULL)"
echo "   - nonce (INTEGER NOT NULL)"
echo ""

echo "2. How to use the program to save data:"
echo ""
echo "   Single node mode (simplified, no PBFT):"
echo "   cargo run -- 0 8000"
echo ""
echo "   This will:"
echo "   - Create blockchain_node_0.db"
echo "   - Fetch Bitcoin price from CoinGecko"
echo "   - Create blocks with market data"
echo "   - Run PBFT consensus (if other nodes are running)"
echo "   - Save committed blocks to SQLite"
echo ""
echo "3. Verify data in SQLite:"
echo ""
echo "   sqlite3 blockchain_node_0.db \"SELECT * FROM blockchain;\""
echo ""
echo "   Or view specific fields:"
echo "   sqlite3 blockchain_node_0.db \"SELECT block_index, hash, data_json FROM blockchain ORDER BY block_index;\""
echo ""
echo "4. Example SQL queries:"
echo ""
echo "   # Count blocks:"
echo "   sqlite3 blockchain_node_0.db \"SELECT COUNT(*) FROM blockchain;\""
echo ""
echo "   # Latest 5 blocks:"
echo "   sqlite3 blockchain_node_0.db \"SELECT block_index, hash FROM blockchain ORDER BY block_index DESC LIMIT 5;\""
echo ""
echo "   # Extract price data from JSON:"
echo "   sqlite3 blockchain_node_0.db \"SELECT block_index, json_extract(data_json, '$[0].price') as price FROM blockchain;\""
echo ""
